namespace LunaDraw.Resources.Strings;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the Visual Studio Code Extension PrateekMahendrakar.resxpress
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class AppResources 
{
	private static global::System.Resources.ResourceManager resourceMan;
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public AppResources()
	{
	}
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (object.ReferenceEquals(resourceMan, null))
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunaDraw.Resources.Strings.AppResources", typeof(AppResources).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Globalization.CultureInfo Culture { get; set; }
	
	/// <summary>
	/// Looks up a localized string similar to Close.
	/// </summary>
	public static string Label_Close => ResourceManager.GetString("Label_Close", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Delete.
	/// </summary>
	public static string Label_Delete => ResourceManager.GetString("Label_Delete", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Eraser.
	/// </summary>
	public static string Label_Eraser => ResourceManager.GetString("Label_Eraser", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Gallery.
	/// </summary>
	public static string Label_Gallery => ResourceManager.GetString("Label_Gallery", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Image.
	/// </summary>
	public static string Label_Image => ResourceManager.GetString("Label_Image", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Movie.
	/// </summary>
	public static string Label_Movie => ResourceManager.GetString("Label_Movie", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Redo.
	/// </summary>
	public static string Label_Redo => ResourceManager.GetString("Label_Redo", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Save.
	/// </summary>
	public static string Label_Save => ResourceManager.GetString("Label_Save", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Select.
	/// </summary>
	public static string Label_Select => ResourceManager.GetString("Label_Select", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Shapes.
	/// </summary>
	public static string Label_Shapes => ResourceManager.GetString("Label_Shapes", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Show Button Labels.
	/// </summary>
	public static string Label_ShowButtonLabels => ResourceManager.GetString("Label_ShowButtonLabels", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Show Layers Panel.
	/// </summary>
	public static string Label_ShowLayersPanel => ResourceManager.GetString("Label_ShowLayersPanel", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Styles.
	/// </summary>
	public static string Label_Styles => ResourceManager.GetString("Label_Styles", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Undo.
	/// </summary>
	public static string Label_Undo => ResourceManager.GetString("Label_Undo", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to View Options.
	/// </summary>
	public static string Label_ViewOptions => ResourceManager.GetString("Label_ViewOptions", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Layers.
	/// </summary>
	public static string Layers_Title => ResourceManager.GetString("Layers_Title", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Add Layer.
	/// </summary>
	public static string ToolTip_AddLayer => ResourceManager.GetString("ToolTip_AddLayer", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Brush Settings.
	/// </summary>
	public static string ToolTip_BrushSettings => ResourceManager.GetString("ToolTip_BrushSettings", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Collapse Layers Panel.
	/// </summary>
	public static string ToolTip_CollapseLayers => ResourceManager.GetString("ToolTip_CollapseLayers", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Delete Selected.
	/// </summary>
	public static string ToolTip_DeleteSelected => ResourceManager.GetString("ToolTip_DeleteSelected", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Eraser.
	/// </summary>
	public static string ToolTip_Eraser => ResourceManager.GetString("ToolTip_Eraser", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Drawing Gallery.
	/// </summary>
	public static string ToolTip_Gallery => ResourceManager.GetString("ToolTip_Gallery", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Import Image.
	/// </summary>
	public static string ToolTip_ImportImage => ResourceManager.GetString("ToolTip_ImportImage", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Toggle Lock.
	/// </summary>
	public static string ToolTip_LayerLock => ResourceManager.GetString("ToolTip_LayerLock", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Toggle Visibility.
	/// </summary>
	public static string ToolTip_LayerVisibility => ResourceManager.GetString("ToolTip_LayerVisibility", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Movie Mode.
	/// </summary>
	public static string ToolTip_MovieMode => ResourceManager.GetString("ToolTip_MovieMode", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Redo.
	/// </summary>
	public static string ToolTip_Redo => ResourceManager.GetString("ToolTip_Redo", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Remove Layer.
	/// </summary>
	public static string ToolTip_RemoveLayer => ResourceManager.GetString("ToolTip_RemoveLayer", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Save Image.
	/// </summary>
	public static string ToolTip_SaveImage => ResourceManager.GetString("ToolTip_SaveImage", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Select Tool.
	/// </summary>
	public static string ToolTip_Select => ResourceManager.GetString("ToolTip_Select", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Shapes.
	/// </summary>
	public static string ToolTip_Shapes => ResourceManager.GetString("ToolTip_Shapes", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Style Settings.
	/// </summary>
	public static string ToolTip_Styles => ResourceManager.GetString("ToolTip_Styles", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Toggle Transparency Mode.
	/// </summary>
	public static string ToolTip_ToggleTraceMode => ResourceManager.GetString("ToolTip_ToggleTraceMode", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Undo.
	/// </summary>
	public static string ToolTip_Undo => ResourceManager.GetString("ToolTip_Undo", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to View Options.
	/// </summary>
	public static string ToolTip_ViewOptions => ResourceManager.GetString("ToolTip_ViewOptions", Culture);
}
