//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaDraw.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunaDraw.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Layers_Title {
            get {
                return ResourceManager.GetString("Layers_Title", resourceCulture);
            }
        }
        
        internal static string ToolTip_AddLayer {
            get {
                return ResourceManager.GetString("ToolTip_AddLayer", resourceCulture);
            }
        }
        
        internal static string ToolTip_RemoveLayer {
            get {
                return ResourceManager.GetString("ToolTip_RemoveLayer", resourceCulture);
            }
        }
        
        internal static string ToolTip_ToggleTraceMode {
            get {
                return ResourceManager.GetString("ToolTip_ToggleTraceMode", resourceCulture);
            }
        }

        internal static string ToolTip_CollapseLayers {
            get {
                return ResourceManager.GetString("ToolTip_CollapseLayers", resourceCulture);
            }
        }

        internal static string ToolTip_LayerVisibility {
            get {
                return ResourceManager.GetString("ToolTip_LayerVisibility", resourceCulture);
            }
        }

        internal static string ToolTip_LayerLock {
            get {
                return ResourceManager.GetString("ToolTip_LayerLock", resourceCulture);
            }
        }

        internal static string Label_Styles {
            get {
                return ResourceManager.GetString("Label_Styles", resourceCulture);
            }
        }

        internal static string Label_Shapes {
            get {
                return ResourceManager.GetString("Label_Shapes", resourceCulture);
            }
        }

        internal static string Label_Image {
            get {
                return ResourceManager.GetString("Label_Image", resourceCulture);
            }
        }

        internal static string Label_Save {
            get {
                return ResourceManager.GetString("Label_Save", resourceCulture);
            }
        }

        internal static string Label_Delete {
            get {
                return ResourceManager.GetString("Label_Delete", resourceCulture);
            }
        }

        internal static string Label_Undo {
            get {
                return ResourceManager.GetString("Label_Undo", resourceCulture);
            }
        }

        internal static string Label_Redo {
            get {
                return ResourceManager.GetString("Label_Redo", resourceCulture);
            }
        }

        internal static string ToolTip_SelectTool {
            get {
                return ResourceManager.GetString("ToolTip_SelectTool", resourceCulture);
            }
        }

        internal static string ToolTip_Styles {
            get {
                return ResourceManager.GetString("ToolTip_Styles", resourceCulture);
            }
        }

        internal static string ToolTip_BrushSettings {
            get {
                return ResourceManager.GetString("ToolTip_BrushSettings", resourceCulture);
            }
        }

        internal static string ToolTip_Shapes {
            get {
                return ResourceManager.GetString("ToolTip_Shapes", resourceCulture);
            }
        }

        internal static string ToolTip_ImportImage {
            get {
                return ResourceManager.GetString("ToolTip_ImportImage", resourceCulture);
            }
        }

        internal static string ToolTip_SaveImage {
            get {
                return ResourceManager.GetString("ToolTip_SaveImage", resourceCulture);
            }
        }

        internal static string ToolTip_Eraser {
            get {
                return ResourceManager.GetString("ToolTip_Eraser", resourceCulture);
            }
        }

        internal static string ToolTip_DeleteSelected {
            get {
                return ResourceManager.GetString("ToolTip_DeleteSelected", resourceCulture);
            }
        }

        internal static string ToolTip_Undo {
            get {
                return ResourceManager.GetString("ToolTip_Undo", resourceCulture);
            }
        }

        internal static string ToolTip_Redo {
            get {
                return ResourceManager.GetString("ToolTip_Redo", resourceCulture);
            }
        }
        
        internal static string Label_ViewOptions {
            get {
                return ResourceManager.GetString("Label_ViewOptions", resourceCulture);
            }
        }

        internal static string Label_ShowLayersPanel {
            get {
                return ResourceManager.GetString("Label_ShowLayersPanel", resourceCulture);
            }
        }

        internal static string Label_ShowButtonLabels {
            get {
                return ResourceManager.GetString("Label_ShowButtonLabels", resourceCulture);
            }
        }

        internal static string ToolTip_ViewOptions {
            get {
                return ResourceManager.GetString("ToolTip_ViewOptions", resourceCulture);
            }
        }

        internal static string Label_Close {
            get {
                return ResourceManager.GetString("Label_Close", resourceCulture);
            }
        }
    }
}
